"""generate the rest of the columns and tables

Revision ID: fde10203f148
Revises: 3846c54a064e
Create Date: 2021-12-22 10:36:41.345397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde10203f148'
down_revision = '3846c54a064e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
